<!-- uLogin widget -->
<?php if($widget === 'window'): ?>
	<a href="#" id="uLogin"><img src="http://ulogin.ru/img/button.png" width=187 height=30 alt="uLogin"/></a>
<?php else: ?>
	<div id="uLogin"></div>
<?php endif;?>
<script src="http://ulogin.ru/js/widget.js?display=<?=$widget; ?>&fields=<?=$fields; ?>&optional=<?=$optional;?>&providers=<?=$providers; ?>&hidden=<?=$hidden; ?>&redirect_uri=http://<?=$url; ?><?php ($callback === true) ? '&callback='.$callback : ''; ?>">
</script>
<!-- /uLogin widget -->